import Stripe from 'stripe'

const STRIPE_SECRET = process.env.NODE_ENV === 'production' ? process.env.STRIPE_SECRET : process.env.TEST_STRIPE_SECRET

let endpointSecret = ''
if (process.env.NODE_ENV === 'production') {
  endpointSecret = process.env.STRIPE_WEBHOOK_ENDPOINT_SECRET as string
} else if (process.env.NODE_ENV === 'production_testsite') {
  endpointSecret = process.env.TEST_STRIPE_WEBHOOK_ENDPOINT_SECRET as string
} else {
  endpointSecret = 'whsec_zlFxiyQM0PsRLg0KambKDW6dPXDNaxRy' // generated by cli
}

export const stripeEndpointSecret = endpointSecret

export default new Stripe(STRIPE_SECRET as string, { apiVersion: '2020-08-27' })
